namespace ManagerAPI.Domain.Enums.SL
{
    public enum StatusLibraryNotificationType
    {
        AddMovie = 67, 
        DeleteMovie = 68, 
        UpdateMovie = 69, 
        AddBook = 70,
        DeleteBook = 71,
        UpdateBook = 72,
        BookReadStatusUpdated = 73,
        MyBookListUpdated = 74, 
        MovieSeenStatusUpdated = 75,
        MyMovieListUpdated = 76,
        AddSeries = 77,
        DeleteSeries = 78,
        UpdateSeries = 79,
        MySeriesListUpdated = 80,
        AddSeason = 81,
        DeleteSeason = 82,
        UpdateSeason = 83,
        AddEpisode = 84,
        DeleteEpisode = 85,
        UpdateEpisode = 86,
        EpisodeSeenStatusUpdated = 87,
        SeasonSeenStatusUpdated = 89,
        SeriesSeenStatusUpdated = 88,
        AddMovieCategory = 90,
        DeleteMovieCategory = 91,
        UpdateMovieCategory = 92,
        AddMovieComment = 93,
        DeleteMovieComment = 94,
        UpdateMovieComment = 95,
        AddSeriesCategory = 96,
        DeleteSeriesCategory = 97,
        UpdateSeriesCategory = 99,
        AddSeriesComment = 99,
        DeleteSeriesComment = 100,
        UpdateSeriesComment = 101
    }
}